### ISSUE TITLE
Match inner-most pair

### ISSUE THREAD

**Issue by CallumHoward** [bounceme/poppy.vim#3]
Thanks for a great plugin, clean and short. I would like to use this plugin to replace the built-in MatchParen, to make the inner-most braces always visible. 
<img width="323" alt="screen shot 2017-06-15 at 10 31 55 am" src="https://user-images.githubusercontent.com/7144420/27160243-1edd1c56-51b6-11e7-8b01-a311481ddeb3.png">

This works great except for the case where the cursor is on a brace:
<img width="323" alt="screen shot 2017-06-15 at 10 32 11 am" src="https://user-images.githubusercontent.com/7144420/27160255-2b40d35c-51b6-11e7-9c99-2d7512f84a9d.png">

I can fix this by adding a 'c' on line 10: `(len(g:poppyhigh) > 1 ? 'r' : '').'cnbW'`, however it doesn't fix the case where the cursor is on the closing brace:
<img width="329" alt="screen shot 2017-06-15 at 10 33 14 am" src="https://user-images.githubusercontent.com/7144420/27160293-71a1ff06-51b6-11e7-8004-529a57cb25e1.png">

Do you have any suggestions?

I have the following config:
```VimL
au cursormoved * call PoppyInit()
let g:poppyhigh = ['MatchParen']
let loaded_matchparen = 1
```

**Comment by bounceme** [comment]
`let g:poppy_point_enable = 1`

**Comment by CallumHoward** [comment]
Perfect! Thanks for the quick response!
